// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Cintervallengths
List Cintervallengths(IntegerVector start_vector, IntegerVector end_vector, int start_scalar, int end_scalar);
RcppExport SEXP _intervalaverage_Cintervallengths(SEXP start_vectorSEXP, SEXP end_vectorSEXP, SEXP start_scalarSEXP, SEXP end_scalarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type start_vector(start_vectorSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type end_vector(end_vectorSEXP);
    Rcpp::traits::input_parameter< int >::type start_scalar(start_scalarSEXP);
    Rcpp::traits::input_parameter< int >::type end_scalar(end_scalarSEXP);
    rcpp_result_gen = Rcpp::wrap(Cintervallengths(start_vector, end_vector, start_scalar, end_scalar));
    return rcpp_result_gen;
END_RCPP
}
// Cweighted_mean
double Cweighted_mean(NumericVector values, IntegerVector durations);
RcppExport SEXP _intervalaverage_Cweighted_mean(SEXP valuesSEXP, SEXP durationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type durations(durationsSEXP);
    rcpp_result_gen = Rcpp::wrap(Cweighted_mean(values, durations));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_intervalaverage_Cintervallengths", (DL_FUNC) &_intervalaverage_Cintervallengths, 4},
    {"_intervalaverage_Cweighted_mean", (DL_FUNC) &_intervalaverage_Cweighted_mean, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_intervalaverage(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
